version: '3.7'

services:

  xkcd_remote:
    build:
      context: ./remote
      dockerfile: Dockerfile
    image: xkcd_remote
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./_data:/app/_data
      - ./_screen:/app/_screen
    env_file:
      - .env

#  screen_server:
#    build:
#      context: ./screen_server
#      dockerfile: Dockerfile
#    image: screen_server
#    ports:
#      - "3000:3000" # Change this if your Node server runs on a different port.
#    volumes:
#      - ./screen_server:/usr/src/app # To enable live-reloading, if needed.#
#    env_file:
#      - .env

#  xkcd_screen
#    build:
#      context: ./screen_server/screen_server.js
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    restart: always

#
#  cloudflared:
#    image: cloudflare/cloudflared:latest
#    command: tunnel
#    depends_on:
#      - xkcd_server
#    volumes:
#      - ./path_to_cloudflared_config:/etc/cloudflared
#    restart: always